Add event to condition

diff --git a/.drone.yml b/.drone.yml
--- a/.drone.yml
+++ b/.drone.yml
@@ -11,13 +11,13 @@ trigger:
   event:
     exclude:
       - promote
-      - tag  
+      - tag
 
 steps:
   - name: fetch
     image: alpine/git
-    commands:      
-      - "git fetch origin +refs/heads/main:"
+    commands:
+      - 'git fetch origin +refs/heads/main:'
 
   - name: install dependencies
     image: &node_image # the version we're targeting for production
@@ -28,7 +28,7 @@ steps:
     commands:
       - npm install
     depends_on:
-      - fetch      
+      - fetch
 
   - name: lint project
     image: *node_image
@@ -55,7 +55,7 @@ steps:
     image: *node_image
     environment:
       SONAR_TOKEN:
-        from_secret: sonar_token        
+        from_secret: sonar_token
       NPM_AUTH_TOKEN:
         from_secret: npm_auth_token
     commands:
@@ -66,7 +66,7 @@ steps:
     when:
       event:
         exclude:
-        - pull_request
+          - pull_request
 
   - name: build project
     image: *node_image
@@ -79,8 +79,8 @@ steps:
         from_secret: kc_realm_dev
       VITE_KC_CLIENTID:
         from_secret: kc_clientid_dev
-      VITE_TIMECARD_API_URL: "https://timecard.dev.callisto-notprod.homeoffice.gov.uk/"
-      VITE_ACCRUALS_API_URL: "https://accruals.dev.callisto-notprod.homeoffice.gov.uk/"
+      VITE_TIMECARD_API_URL: 'https://timecard.dev.callisto-notprod.homeoffice.gov.uk/'
+      VITE_ACCRUALS_API_URL: 'https://accruals.dev.callisto-notprod.homeoffice.gov.uk/'
     commands:
       - npm run build
     depends_on:
@@ -97,18 +97,18 @@ steps:
       followtags: true
     when:
       event:
-       - push
+        - push
       branch:
-       - main  
-    depends_on:      
+        - main
+    depends_on:
       - sonar analysis
-  
+
   - name: upload to S3
     image: amazon/aws-cli
     commands:
       - >
         aws s3 cp 
-        --recursive ./dist/ s3://ho-callisto-dev/dev/main    
+        --recursive ./dist/ s3://ho-callisto-dev/dev/main
     environment:
       AWS_DEFAULT_REGION: eu-west-2
       AWS_ACCESS_KEY_ID:
@@ -117,26 +117,26 @@ steps:
         from_secret: s3_aws_secret_access_key
     when:
       event:
-       - push
+        - push
       branch:
-       - main  
+        - main
     depends_on:
       - git tag push
 
   - name: url check
-    pull: if-not-exists    
-    image: alpine/curl:3.14   
-    commands:       
-    - curl -s https://raw.githubusercontent.com/UKHomeOffice/callisto-ui-nginx/main/scripts/is-url-up.sh >up.sh
-    - chmod +x ./up.sh
-    - ./up.sh https://web.dev.callisto-notprod.homeoffice.gov.uk/index.html
+    pull: if-not-exists
+    image: alpine/curl:3.14
+    commands:
+      - curl -s https://raw.githubusercontent.com/UKHomeOffice/callisto-ui-nginx/main/scripts/is-url-up.sh >up.sh
+      - chmod +x ./up.sh
+      - ./up.sh https://web.dev.callisto-notprod.homeoffice.gov.uk/index.html
     when:
       event:
-       - push
+        - push
       branch:
-       - main  
+        - main
     depends_on:
-      - upload to S3    
+      - upload to S3
 
 ---
 kind: pipeline
@@ -159,7 +159,7 @@ trigger:
 steps:
   - name: promote to test check
     image: alpine:latest
-    commands:    
+    commands:
       - echo Cannot promote from non 'main' branch
       - exit 1
     when:
@@ -178,8 +178,8 @@ steps:
         from_secret: kc_realm_test
       VITE_KC_CLIENTID:
         from_secret: kc_clientid_test
-      VITE_TIMECARD_API_URL: "https://timecard.test.callisto-notprod.homeoffice.gov.uk/"
-      VITE_ACCRUALS_API_URL: "https://accruals.test.callisto-notprod.homeoffice.gov.uk/"                        
+      VITE_TIMECARD_API_URL: 'https://timecard.test.callisto-notprod.homeoffice.gov.uk/'
+      VITE_ACCRUALS_API_URL: 'https://accruals.test.callisto-notprod.homeoffice.gov.uk/'
     commands:
       - npm ci
       - npm run build
@@ -191,7 +191,7 @@ steps:
     commands:
       - >
         aws s3 cp 
-        --recursive ./dist/ s3://ho-callisto-dev/test/main   
+        --recursive ./dist/ s3://ho-callisto-dev/test/main
     environment:
       AWS_DEFAULT_REGION: eu-west-2
       AWS_ACCESS_KEY_ID:
@@ -218,9 +218,9 @@ trigger:
     - promote
   target:
     include:
-    - production
+      - production
     exclude:
-    - test
+      - test
 
 steps:
   - name: environment check
@@ -235,29 +235,29 @@ steps:
           - production
 
   - name: successful build check
-    pull: if-not-exists    
+    pull: if-not-exists
     image: drone/cli:1.6.2-alpine
     environment:
       DRONE_SERVER: https://drone-gh.acp.homeoffice.gov.uk
       DRONE_TOKEN:
-        from_secret: drone_token        
+        from_secret: drone_token
     commands:
-    - |        
-      PAGE=1
-      SUCCESSFUL_BUILDS=''      
-      while [ "$PAGE" -le 10 ]; do 
-        SUCCESSFUL_BUILDS="$(drone build ls --format '{{.Number}}' $DRONE_REPO --branch main --status success --event push --limit 100 --page $PAGE)"
-        if [ `echo $SUCCESSFUL_BUILDS | grep -c $DRONE_BUILD_PARENT` -gt 0 ]; then
-          echo 'Found successful build.'
-          exit 0
-        fi 
-        PAGE="$((PAGE+1))"
-      done
-      echo 'No succcessful build found.'
-      exit 1
+      - |
+        PAGE=1
+        SUCCESSFUL_BUILDS=''      
+        while [ "$PAGE" -le 10 ]; do 
+          SUCCESSFUL_BUILDS="$(drone build ls --format '{{.Number}}' $DRONE_REPO --branch main --status success --event push --limit 100 --page $PAGE)"
+          if [ `echo $SUCCESSFUL_BUILDS | grep -c $DRONE_BUILD_PARENT` -gt 0 ]; then
+            echo 'Found successful build.'
+            exit 0
+          fi 
+          PAGE="$((PAGE+1))"
+        done
+        echo 'No succcessful build found.'
+        exit 1
     depends_on:
       - environment check
- 
+
   - name: build for prod
     image: node:16.15.0
     environment:
@@ -269,8 +269,8 @@ steps:
         from_secret: kc_realm_prod
       VITE_KC_CLIENTID:
         from_secret: kc_clientid_prod
-      VITE_TIMECARD_API_URL: "https://timecard.callisto.homeoffice.gov.uk/"
-      VITE_ACCRUALS_API_URL: "https://accruals.callisto.homeoffice.gov.uk/"                        
+      VITE_TIMECARD_API_URL: 'https://timecard.callisto.homeoffice.gov.uk/'
+      VITE_ACCRUALS_API_URL: 'https://accruals.callisto.homeoffice.gov.uk/'
     commands:
       - npm ci
       - npm run build
@@ -284,7 +284,7 @@ steps:
         aws s3 cp 
         --recursive ./dist/ s3://ho-callisto/main
         --sse aws:kms
-        --sse-kms-key-id $${AWS_KMS_KEY}      
+        --sse-kms-key-id $${AWS_KMS_KEY}
     environment:
       AWS_DEFAULT_REGION: eu-west-2
       AWS_ACCESS_KEY_ID:
@@ -307,9 +307,9 @@ trigger:
     - failure
 
 depends_on:
-  - callisto-ui  
+  - callisto-ui
   - callisto-ui-test-deploy
-  - callisto-ui-prod-deploy    
+  - callisto-ui-prod-deploy
 
 slack: &slack
   image: plugins/slack
@@ -318,8 +318,8 @@ slack: &slack
       from_secret: SLACK_WEBHOOK_URL
     channel: callisto-tech-notifications
     username: Drone
-  
-steps:  
+
+steps:
   - name: slack_urgent
     image: plugins/slack
     settings:
@@ -328,15 +328,18 @@ steps:
       channel: callisto-urgent-tech-notifications
       username: Drone
       template: |
-          <${DRONE_BUILD_LINK}|Build #{{build.number}}> failed :alert:
-          Commit: <${DRONE_REPO_LINK}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}> - {{{ trim build.message }}}
-          Repo: {{ repo.name }}
-          Branch: <${DRONE_REPO_LINK}/commits/{{ build.branch }}|{{ build.branch }}>
-          Author: {{ build.author }}
-          <https://sonarcloud.io/dashboard?id=callisto-ui&branch={{ build.branch }}&resolved=false|SonarCloud Analysis Report>
-          {{build.link}}
-    when: 
-      status: 
+        <${DRONE_BUILD_LINK}|Build #{{build.number}}> failed :alert:
+        Commit: <${DRONE_REPO_LINK}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}> - {{{ trim build.message }}}
+        Repo: {{ repo.name }}
+        Branch: <${DRONE_REPO_LINK}/commits/{{ build.branch }}|{{ build.branch }}>
+        Author: {{ build.author }}
+        <https://sonarcloud.io/dashboard?id=callisto-ui&branch={{ build.branch }}&resolved=false|SonarCloud Analysis Report>
+        {{build.link}}
+    when:
+      event:
+        - push
+        - promote
+      status:
         - failure
 
   - name: slack_build
@@ -355,7 +358,7 @@ steps:
         <https://sonarcloud.io/dashboard?id=callisto-ui&branch={{ build.branch }}&resolved=false|SonarCloud Analysis Report>
         {{build.link}}
     when:
-      event: 
+      event:
         - push
       status:
         - success
@@ -369,11 +372,10 @@ steps:
           :rocket: Successful *{{uppercasefirst build.deployTo}}* deployment for *{{repo.name}} build #{{build.number}}*.          
         {{else}}
           :zombie: Problem *{{uppercasefirst build.deployTo}}* deployment failed for *{{repo.name}}* <${DRONE_BUILD_LINK}| build #{{build.number}}>.
-        {{/success}}       
+        {{/success}}
     when:
-      event: 
+      event:
         - promote
       status:
         - success
         - failure
-
